#!/bin/bash

echo "";
echo "iPod Memos and MFMusicLibrary by H2CO3";
echo "";
echo "Please don't forget to donate if you";
echo "liked this app! Thank you very much!";
echo "";
echo '   ###    RESPRING NOW    ###';
echo "";
